### ISSUE TITLE
Consider using `slim-buster` tag instead

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#1046]
`-alpine` is great and all, but `-slim-buster` allows faster build time while is not much bigger. 

alpine: https://hub.docker.com/layers/python/library/python/3.8.1-alpine3.11/images/sha256-41b1c1eeecbc15decc561bff9b39ea82f1283e8f7c0a9cba88278689fce55b64 34mb
slim buster: https://hub.docker.com/layers/python/library/python/3.8.1-slim-buster/images/sha256-8b5ef97385dcf8d75b0273e67dfe0f63f9dbbfc6caa9663dabd2f05bc01027b7 59mb

We need to measure build times and compare them.

Related: 
https://pythonspeed.com/articles/base-image-python-docker-images/

**Comment by wwarne** [comment]
I did some tests and here is my results.


I didn't have any problems with alpine even though I use a lot of python packages in my project. But then I installed pandas the building time just spiked. It takes 40 minutes on gitlab CI to build. Thanks to **--cache-from** directive this took 40 minutes only if I install new package or update versions of installed ones.

The more you need to use some packages which depend on C libraries the more build time you need for alpine, because it has to compile everything from scratch. Slim-buster uses precompiled parts so it builds much faster. 


| Description                                                       | Alpine          | Alpine         | Slim-buster     | Slim-buster     |
|-------------------------------------------------------------------|-----------------|----------------|-----------------|-----------------|
|                                                                   | Build time, min | Image size, MB | Build time, min |  Image size, MB |
| Just after creating new project, without any additional packages. | 5.8             | 487            | 4.22            | 578             |
| With additional Pillow package (+ libjpg and zlib)         | 5.29            | 494            | 4.23            | 585             |
| With pandas and all packages it is needed                         | 25.41           | 890            | 4.51            | 710             |

Probably I can decrease the size of Alpine-based image if I reorganize RUN commands. Because in slim-buster I deleted build-base packages and in alpine they are stays in image so don't take slim-buster image size as a smaller one :)

**Comment by blaise-sumo** [comment]
Itamar Turner-Trauring describes this in some detail:
https://pythonspeed.com/articles/alpine-docker-python/
also, Alpine does not use glibc and a lot of packages depend on it.

**Comment by sobolevn** [comment]
My current `Dockerfile`:

```Dockerfile
# This Dockerfile uses multi-stage build to customize DEV and PROD images:
# https://docs.docker.com/develop/develop-images/multistage-build/

FROM python:3.7.6-slim-buster as development_build

LABEL maintainer="sobolevn@wemake.services"
LABEL vendor="wemake.services"

ARG DJANGO_ENV

ENV DJANGO_ENV=${DJANGO_ENV} \
  # python:
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  # pip:
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # dockerize:
  DOCKERIZE_VERSION=v0.6.1 \
  # tini:
  TINI_VERSION=v0.18.0 \
  # poetry:
  POETRY_VERSION=1.0.3 \
  POETRY_VIRTUALENVS_CREATE=false


# System deps:
RUN apt-get update \
  && apt-get install --no-install-recommends -y \
    bash \
    build-essential \
    curl \
    freetds-dev \
    unixodbc-dev \
    gcc \
    gettext \
    git \
    libffi-dev \
    libxml2-dev \
    libxslt-dev \
    libpq-dev \
    wget \
  # Cleaning cache:
  && apt-get clean && rm -rf /var/lib/apt/lists/* \
  # Installing `dockerize` utility:
  # https://github.com/jwilder/dockerize
  && wget "https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz" \
  && tar -C /usr/local/bin -xzvf "dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz" \
  && rm "dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz" && dockerize --version \
  # Installing `tini` utility:
  # https://github.com/krallin/tini
  && wget -O /usr/local/bin/tini "https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini" \
  && chmod +x /usr/local/bin/tini && tini --version \
  # Installing `poetry` package manager:
  # https://github.com/python-poetry/poetry
  && pip install "poetry==$POETRY_VERSION" && poetry --version

# Copy only requirements, to cache them in docker layer
WORKDIR /pysetup
COPY ./poetry.lock ./pyproject.toml /pysetup/

# Project initialization:
RUN echo "$DJANGO_ENV" && poetry install $(if [ "$DJANGO_ENV" = 'production' ]; then echo '--no-dev'; fi) --no-interaction --no-ansi

# This is a special case. We need to run this script as an entry point:
COPY ./docker/django/entrypoint.sh /docker-entrypoint.sh

# This is also a special case, here we override default `mssql` configuration:
COPY ./docker/django/mssql /etc

# Setting proper permissions:
RUN chmod +x '/docker-entrypoint.sh'

# This dir will become the mountpoint of development code:
WORKDIR /code
ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]


# The following stage is only for Prod:
# https://wemake-django-template.readthedocs.io/en/latest/pages/template/production.html

FROM development_build as production_build

COPY . /code

```

**Comment by sobolevn** [comment]
Maybe we can run `poetry cache clear --all .` after the install process?
