### ISSUE TITLE
Consider adding statement timeout

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#1064]
https://hakibenita.com/9-django-tips-for-working-with-databases#statement-timeout

**Comment by sobolevn** [comment]
Code sample:

```python
# wsgi.py

from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def setup_postgres(connection, **kwargs):
    if connection.vendor != 'postgresql':
        return

    # Timeout statements after 30 seconds.
    with connection.cursor() as cursor:
        cursor.execute("SET statement_timeout TO 30000;")
```

**Comment by sobolevn** [comment]
Discussion: https://twitter.com/AdamChainz/status/1240582056259792898

**Comment by sobolevn** [comment]
We can probably add this to `django-test-migrations`
What do you think @skarzi ?

**Comment by skarzi** [comment]
that's really nice article :+1: 

What exactly do you want to add?
Some check to be sure that this value is set when using DB that supports this option?
Do you want just set this value before starting migrations tests?
Or maybe something else?

First option seems really nice, because it's better to set such value (preferably with some logging - for sure it's possible in PostgreSQL to log time-outed queries) than not.
About second point, I think it needs to be discussed more deeply, e.g I think it should be optional, because maybe some users needs bigger value, because they are doing some more intensive, long lasting DB operation in 1 of their migrations etc

**Comment by sobolevn** [comment]
I was thinking about 

> Some check to be sure that this value is set when using DB that supports this option?

We can just check that value is there if the check is active.

**Comment by skarzi** [comment]
sure :+1: 
I will add issue for that and look at it closer today's evening
