### ISSUE TITLE
makemigrations permission denied.

### ISSUE THREAD

**Issue by mazlum** [wemake-services/wemake-django-template#1518]
Hello,

When I run in the following command in development mode. 
```bash
docker-compose -f docker-compose.yml -f docker-compose.dev.yml run --rm web python manage.py makemigrations
```
I get in the following error; "Permission denied: '/code/server/apps/main/migrations/0002_blogpost_is_ok.py'" 

I'm using Linux.

**Comment by sobolevn** [comment]
What's in `docker-compose.dev.yml`?

**Comment by mazlum** [comment]
I did not change anything in docker-compose.dev.yml. I just created project with cookiecutter. After that I just only add is_ok=models.BooleanField(default=True) in blogpost model. And i run the command what I said in the previous comment.

**Comment by sobolevn** [comment]
But we don't have `docker-compose.dev.yml` in this repo: https://github.com/wemake-services/wemake-django-template/tree/master/%7B%7Bcookiecutter.project_name%7D%7D

Do you mean `docker-compose.override.yml`?

**Comment by mazlum** [comment]
Yes @sobolevn I'm sorry :)

It's docker-compose.ovverride.yml

**Comment by sobolevn** [comment]
Can you please share what privilages does this file have in your setup?

**Comment by mazlum** [comment]
I just installed ubuntu for testing as virtual machine. And I'm sharing with you screenshots.

![image](https://user-images.githubusercontent.com/5855630/112338194-a63bfc00-8ccf-11eb-88db-fa38b3fe8401.png)

![image](https://user-images.githubusercontent.com/5855630/112338259-b6ec7200-8ccf-11eb-9f19-e055c5cbc222.png)

![image](https://user-images.githubusercontent.com/5855630/112338412-d5526d80-8ccf-11eb-88f5-b12d576e2877.png)

**Comment by DenizParlak** [comment]
docker-compose and Dockerfile syntax have different behavior for 'volume'. Bind mounted volumes will keep the current permissions that are already set on the host.

When you check the directory structure in the container, that shows 1000:1000 UID/GID because of your host-level permissions. At this point, UID or GID doesn't matter; they are only referencing actual user/group pairs.

So, this Docker structure, it's using a web user with 999 UID, and it conflicts with the host UID, which is used for the current directory.

With 'docker run ...' that issue may bypass via --v $(pwd):/code ... but in this scenario, before run docker-compose first change the permission of related directories or all structure like:

chown -R 999:999 .

After that, it should be work.

**Comment by monosans** [comment]
An identical problem occurs when saving media. Is there any progress on this issue?
