### ISSUE TITLE
Moving to Django 2.1

### ISSUE THREAD

**Issue by DmytroLitvinov** [wemake-services/wemake-django-template#500]
As we know Django 2.1(LTS version) [was released](https://docs.djangoproject.com/en/2.1/releases/2.1/).

Maybe we should start to think about that and try to move template to 2.1 version.
What do you think, @sobolevn ?

**Comment by sobolevn** [comment]
I have not catch that! Yes, it is time to move on!

@DmytroLitvinov do you want to do the honors?

**Comment by DmytroLitvinov** [comment]
Hey @sobolevn .
Sorry for such long response.
I just rechecked and found that [Django 2.2 will be LTS version.](https://www.djangoproject.com/download/#supported-versions)
Probably we can close this issue I think.

**Comment by AndrewPix** [comment]
I think the project with "Bleeding edge django template" description should have at least django 2.0 version. Then we can easily upgrade to django 2.2 LTS from 2.0

**Comment by sobolevn** [comment]
@AndrewPix nice point. We stick to LTS version just because of the maintenance. It is really easy to support project with the stable framework that ones with constant changes in the core.

I do not actually see any features in `django@2` that are so worth upgrading right now.
And finally, it is an easy thing to do for an end user if needed.

Closing.
