### ISSUE TITLE
Database engine variables in a more general way

### ISSUE THREAD

**Issue by folt** [wemake-services/wemake-django-template#747]
Hi.
I faced a very hard work when changing the database engine.
[Maybe we should call these variables in a more general way](https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/server/settings/components/common.py#L79)?

example:
`DB_NAME=mydb`
`DB_USER=myuser`
`DB_PASSWORD=mypass`

**Comment by sobolevn** [comment]
Hi, @folt ! Thanks for bringing this up. The reason behind this naming is that `postgres` requires these env vars: see https://hub.docker.com/_/postgres

So, changing it is not possible.

But! If anything is not clear, so the docs should be improved. I guess, in this particular case we can add a comment section to `.env.template` somewhere near the `POSTGRES_DB` variable with the link to the `postgres-docker` page.

Is this solution fine with you? I would appreciate a PR from you.

Also, changing / adding databases is quite popular. We can also cover this in a separate PR.
I will write a tutorial about it. Thanks for raising this issue!

**Comment by sobolevn** [comment]
Please, comment if my solution is not clear enough.

**Comment by folt** [comment]
I believe that this will not be enough.
I suggest adding a database selection and cache system to the project generation template.

> Please, comment if my solution is not clear enough.

**Comment by sobolevn** [comment]
What kind of database and cache section are you talking about?
Like here:
<img width="121" alt="Снимок экрана 2019-06-09 в 23 14 11" src="https://user-images.githubusercontent.com/4660275/59163638-509f5b00-8b0c-11e9-8d93-6b351c4f4386.png">

And add new menu items:
- Database
- Cache

? 

I am not sure what to write there, since: database setup is pretty simple and we don't use cache by default. What's your vision on this?

**Comment by folt** [comment]
Database settings should be attributed to the [django environment settings](https://wemake-django-template.readthedocs.io/en/latest/pages/template/django.html#configuration).
In the django section is to add the item Database and Cache.

> I am not sure what to write there, since: database setup is pretty simple and we don't use cache by default. What's your vision on this?

I suggest putting the database and cache settings in the project creation script using a template. Selection of the database driver to provide the developer. A similar example can be seen [here](https://github.com/pydanny/cookiecutter-django/blob/master/cookiecutter.json#L20).

**Comment by sobolevn** [comment]
> Database settings should be attributed to the django environment settings.
In the django section is to add the item Database and Cache.

Can you please explain this part deeply? I don't get it at the moment.

> I suggest putting the database and cache settings in the project creation script using a template. Selection of the database driver to provide the developer. A similar example can be seen here.

Nope, this is out of scope of this project. Because we try to provide the best experience with the tooling and structure. Not the plugins and infrastructure. 

Moreover, it will overly complicate our test setup and codebase with things we don't use. And it will become outdated pretty soon. We stick to `postgres` + `redis` almost for every project.

**Comment by folt** [comment]
> Can you please explain this part deeply? I don't get it at the moment.

> I am not sure what to write there, since: database setup is pretty simple and we don't use cache by default. What's your vision on this?

I support this decision

> Nope, this is out of scope of this project. Because we try to provide the best experience with the tooling and structure. Not the plugins and infrastructure.
> 
> Moreover, it will overly complicate our test setup and codebase with things we don't use. And it will become outdated pretty soon. We stick to postgres + redis almost for every project.

Can you give more details?
I easily changed the database driver in the template. For this, I needed to change the database settings, the settings of the docker and some dependencies in poetry. The whole CI works fine.

**Comment by sobolevn** [comment]
Thanks for the suggestion! 👍 

But, I am closing it as out-of-scope.
The point of this template is to provide minimal valuable example.
And we do not want to cover other databases and caches.
That is something user should do.
