### ISSUE TITLE
Enhance layout to prevent nasty shadowing of installed module

### ISSUE THREAD

**Issue by pakal** [wemake-services/wemake-django-template#809]
As explained here https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure, letting the "server" package at the root of the directory can bring all kinds of troubles, in particular when running tests with tox : the installed package is shadowed by the repository's package, making it possible to upload a broken package (with missing files) to pypi.

Maybe using a src/ directory (and a conftest.py in it so that pytest finds it when not run from tests/) would be better?

**Comment by sobolevn** [comment]
Thanks for the suggestion. I will dig into it.

In my experience, I never had any issues with the package names.
But, I know that @AlwxSin did, there was so `poetry` related bug.

I am pretty sure that not a lot of people use `tox` with this setup. Since `tox` is created mainly for libraries, not projects. And I am pretty sure that almost no one uploads these packages to pypi, since it does not seem reasonable.

But, as I said, I will research this idea. Thanks! 👍

**Comment by AlwxSin** [comment]
Bug with poetry was about naming the main directory (`server` in our case) differently from the project name (`cookiecutter.project_name`). 
But the bug was fixed, it shouldn't be a problem.

**Comment by pakal** [comment]
You're right, for projects and not libs, tox support is not really important. 
Packaging guides should stop advising to put packages at the root, most tox tests never test the really installed package, considered how pythonpaths work.
